name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: true
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4.1.1

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish to Reposolite
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_reposoliteUsername: ${{ secrets.REPOSOLITE_USERNAME }}
          ORG_GRADLE_PROJECT_reposolitePassword: ${{ secrets.REPOSOLITE_PASSWORD }}