name: Build main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run BuildTools
        uses: SpraxDev/Action-SpigotMC@v3
        with:
          versions: 1.17.1
          forceRun: false
          buildToolProvider: SpigotMC

      - name: Build with Maven
        run: mvn -B package --file pom.xml
